# Generated by Django 5.0 on 2025-08-21 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MrConsultation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField()),
                ('date_part', models.SmallIntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('patient_id', models.IntegerField()),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('location_type_id', models.IntegerField(blank=True, null=True)),
                ('accompanying_hcp_id', models.IntegerField(blank=True, null=True)),
                ('external_consultant', models.CharField(blank=True, max_length=50, null=True)),
                ('consultation_type', models.SmallIntegerField(blank=True, null=True)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('travel_time', models.SmallIntegerField(blank=True, null=True)),
                ('appointment_slot_id', models.IntegerField(blank=True, null=True)),
                ('data_source_id', models.SmallIntegerField()),
                ('policy_id', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField()),
            ],
            options={
                'db_table': '"emispatient"."mr_consultation"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MrEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('assigned_date', models.DateTimeField()),
                ('date_part', models.IntegerField()),
                ('event_author_id', models.IntegerField(blank=True, null=True)),
                ('consultation_id', models.IntegerField(blank=True, null=True)),
                ('descriptive_text', models.TextField(blank=True, null=True)),
                ('display_term', models.CharField(blank=True, max_length=200, null=True)),
                ('episodicity', models.SmallIntegerField(blank=True, null=True)),
                ('event_type_id', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('term_id', models.CharField(blank=True, max_length=50, null=True)),
                ('numeric_operator', models.CharField(blank=True, max_length=10, null=True)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('numeric_units', models.CharField(blank=True, max_length=50, null=True)),
                ('numeric_minimum', models.FloatField(blank=True, null=True)),
                ('numeric_maximum', models.FloatField(blank=True, null=True)),
                ('min_range_operator', models.CharField(blank=True, max_length=10, null=True)),
                ('max_range_operator', models.CharField(blank=True, max_length=10, null=True)),
                ('abnormal', models.BooleanField(blank=True, null=True)),
                ('external_consultant', models.CharField(blank=True, max_length=50, null=True)),
                ('gms', models.BooleanField(blank=True, null=True)),
                ('data_source', models.SmallIntegerField()),
                ('policy_id', models.IntegerField(blank=True, null=True)),
                ('templateinstance_id', models.IntegerField(blank=True, null=True)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('template_component_name', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField()),
                ('reason_for_deletion', models.CharField(blank=True, max_length=200, null=True)),
                ('record_date', models.DateTimeField()),
                ('guid', models.UUIDField(default=uuid.uuid4)),
                ('src_xml', models.IntegerField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('assigned_date_time_zone', models.IntegerField(blank=True, null=True)),
                ('event_original_author', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('inserted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"emispatient"."mr_event"',
                'managed': False,
            },
        ),
    ]
