# Generated by Django 4.0 on 2026-02-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_texsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadSnomedIntMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_code', models.CharField(db_index=True, max_length=10)),
                ('concept_id', models.TextField(db_index=True)),
                ('term', models.TextField()),
                ('description_id', models.TextField(db_index=True)),
            ],
            options={
                'db_table': 'read_snomed_int_map',
            },
        ),
        migrations.CreateModel(
            name='ReadSnomedUkMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_code', models.CharField(db_index=True, max_length=10)),
                ('concept_id', models.TextField(db_index=True)),
                ('term', models.TextField()),
                ('description_id', models.TextField(db_index=True)),
            ],
            options={
                'db_table': 'read_snomed_uk_map',
            },
        ),
        migrations.AddIndex(
            model_name='readsnomedukmap',
            index=models.Index(fields=['read_code'], name='read_snomed_read_co_b3f072_idx'),
        ),
        migrations.AddIndex(
            model_name='readsnomedukmap',
            index=models.Index(fields=['concept_id'], name='read_snomed_concept_5bcf13_idx'),
        ),
        migrations.AddIndex(
            model_name='readsnomedukmap',
            index=models.Index(fields=['description_id'], name='read_snomed_descrip_1bfdab_idx'),
        ),
        migrations.AddConstraint(
            model_name='readsnomedukmap',
            constraint=models.UniqueConstraint(fields=('read_code', 'concept_id', 'description_id'), name='uq_read_uk_readcode_concept_desc'),
        ),
        migrations.AddIndex(
            model_name='readsnomedintmap',
            index=models.Index(fields=['read_code'], name='read_snomed_read_co_966f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='readsnomedintmap',
            index=models.Index(fields=['concept_id'], name='read_snomed_concept_de9eac_idx'),
        ),
        migrations.AddIndex(
            model_name='readsnomedintmap',
            index=models.Index(fields=['description_id'], name='read_snomed_descrip_293849_idx'),
        ),
        migrations.AddConstraint(
            model_name='readsnomedintmap',
            constraint=models.UniqueConstraint(fields=('read_code', 'concept_id', 'description_id'), name='uq_read_int_readcode_concept_desc'),
        ),
    ]
